import './globals.css';
import React from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import CustomToast from '@/components/utils/CustomToast';
import JotaiProvider from '@/providers/jotai-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <JotaiProvider>{children}</JotaiProvider>
        <CustomToast />
      </body>
    </html>
  );
};

export default RootLayout;
